### ISSUE TITLE
Can't resolve '@swagger-api/apidom-json-pointer' in latest release

### ISSUE THREAD

**Issue by benjdlambert** [swagger-api/apidom#4539] opened 2024-11-21 12:19 UTC
Looks like the latest release that went out appears to have broken our tests. 

```
Error: Failed to compile '../../node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor/toolbox.mjs':
  Module not found: Error: Can't resolve '@swagger-api/apidom-json-pointer' in '/tmp/backstage-e2e-wwR5QI/test-app/node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor'
```

Wondering if this is a bad publish?

Additional build logs here: https://github.com/backstage/backstage/actions/runs/11952606327/job/33318690026

**Comment by IagorSs** [comment] 2024-11-21 13:26
Same error here

**Comment by paztis** [comment] 2024-11-21 15:11
swagger-client webpack bundling totally fails also for us

**Comment by benjdlambert** [comment] 2024-11-21 15:20
Looks like adding a resolution for `@swagger-api/apidom-json-pointer` works for us, but not ideal.

```diff
   "resolutions": {
     "@types/react": "^18",
     "@types/react-dom": "^18"
     "@types/react-dom": "^18",
+    "@swagger-api/apidom-json-pointer": "1.0.0-alpha.10"
```

**Comment by paztis** [comment] 2024-11-21 15:31
in fact it may be the same for all you optional dependencies.
```
  "optionalDependencies": {
    "@swagger-api/apidom-error": "^1.0.0-alpha.1",
    "@swagger-api/apidom-json-pointer": "^1.0.0-alpha.1",
    "@swagger-api/apidom-ns-asyncapi-2": "^1.0.0-alpha.1",
    "@swagger-api/apidom-ns-openapi-2": "^1.0.0-alpha.1",
    "@swagger-api/apidom-ns-openapi-3-0": "^1.0.0-alpha.1",
    "@swagger-api/apidom-ns-openapi-3-1": "^1.0.0-alpha.1",
    "@swagger-api/apidom-ns-workflows-1": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-api-design-systems-json": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-api-design-systems-yaml": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-asyncapi-json-2": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-asyncapi-yaml-2": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-json": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-openapi-json-2": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-openapi-json-3-0": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-openapi-json-3-1": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-openapi-yaml-2": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-openapi-yaml-3-0": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-openapi-yaml-3-1": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-workflows-json-1": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-workflows-yaml-1": "^1.0.0-alpha.1",
    "@swagger-api/apidom-parser-adapter-yaml-1-2": "^1.0.0-alpha.1"
  },
```

otherwise you must upgrade swagger-client to the beta version

**Comment by debabin** [comment] 2024-11-22 09:13
![image](https://github.com/user-attachments/assets/f4c58a36-aef7-4ff8-9762-67257b151e80)

same, using "swagger-ui-react": "^5.18.2". the application breaks with version 5 of swagger-ui-react. resolutions did not help

**Comment by char0n** [comment] 2024-11-22 11:25
Hi everybody.

Working on it.

**Comment by char0n** [comment] 2024-11-22 11:25
First fix provided in https://github.com/swagger-api/apidom/releases/tag/v1.0.0-beta.1

Next fix comming in couple of minutes.

**Comment by char0n** [comment] 2024-11-22 11:32
Release in progress https://github.com/swagger-api/apidom/actions/runs/11971775640/job/33377284820

**Comment by char0n** [comment] 2024-11-22 12:07
Fix released in https://github.com/swagger-api/apidom/releases/tag/v1.0.0-beta.2.

Thanks for you patience.

**Comment by paztis** [comment] 2024-11-22 13:13
Wait. The problem is on 1.0.0-alpha.10 version, not on beta.0

If you didn't upgrade swagger-client, you must deliver a 1.0.0-alpha.11 with fixes

**Comment by paztis** [comment] 2024-11-22 13:26
All the issue I explain you is due to alpha.10

I. Alpha 10 delivery, you declare optionalDep of ^1.0.0-alpha.1

So if anyone install an alpha.10 it get beta.0 of the deps installed and this is what is crashing

As swagger-client continue to point to last alpha, your fix will not resolve anything 

The only solution is to release an alpha.11 with the fix or re-release alpha 10

**Comment by paztis** [comment] 2024-11-22 13:28
With your current management, each time you release a beta with breaking changes, all the alpha are broken

**Comment by paztis** [comment] 2024-11-22 13:30
The problem is mostly visible in the minirepos

**Comment by char0n** [comment] 2024-11-22 13:34
Ok thank you I understand how, it's here: https://github.com/swagger-api/apidom/blob/main/packages/apidom-reference/package.json#L270. There is no upper boundary. So the `apidom-reference@alpha` might pull in the beta.

**Comment by paztis** [comment] 2024-11-22 13:35
Yes that's it

**Comment by char0n** [comment] 2024-11-22 13:37
What I can do is fix that in next beta release and release a new swagger-client that fix beta. You can then pin your swagger-client to safeguard for future. alpha and beta are fully compatible and there is no plan to break the compatibility in beta. We'll not be releasing fixed alpha release. Would that work for you?

**Comment by paztis** [comment] 2024-11-22 13:38
If it is BWC it's on for me

**Comment by jefag** [comment] 2024-11-22 17:32
Hey folks, we're seeing the below in our build, seems related to this thread?  Is there a workaround?  

I've tried the suggestions in the thread, no luck.

```
Error: Cannot find module '/workspace/node_modules/@swagger-api/apidom-parser-adapter-api-design-systems-json/src/adapter.cjs'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:[11](https://github.com/voteagora/agora-next/actions/runs/11977257933/job/33394736599#step:4:12)81:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:[12](https://github.com/voteagora/agora-next/actions/runs/11977257933/job/33394736599#step:4:13)35:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/workspace/node_modules/@swagger-api/apidom-reference/src/parse/parsers/api-design-systems-json/index.cjs:7:48)
    at Module._compile (node:internal/modules/cjs/loader:[13](https://github.com/voteagora/agora-next/actions/runs/11977257933/job/33394736599#step:4:14)76:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/workspace/node_modules/@swagger-api/apidom-parser-adapter-api-design-systems-json/package.json'
}
```

**Comment by char0n** [comment] 2024-11-25 12:13
> If it is BWC it's ok for me

Explicit upper bound defined inhttps://github.com/swagger-api/apidom/pull/4556

**Closed** 2024-11-25 12:50 UTC
Labels: bug, ApiDOM
