### ISSUE TITLE
apidom-ls / apidom - Default to schema element for message payload when empty node

### ISSUE THREAD

**Issue by frantuma** [swagger-api/apidom#1077] opened 2022-01-17 15:25 UTC
@frantuma commented on [Mon Jan 17 2022](https://github.com/swagger-api/oss-planning/issues/501)

Currently an "empty" payload is not parsed as `schema` element using `refractorPluginReplaceEmptyElement` as done for other empty elements. Goal of this ticket is applying the same mechanism also to payload.

Note. The possible reason for this behavior is `payload` type being `any` therefore admitting also non `schema` types.

```
asyncapi: '2.2.0'
components:
  messages:
    lightMeasured:
      payload:
        
```

---

@frantuma commented on [Mon Jan 17 2022](https://github.com/swagger-api/oss-planning/issues/501#issuecomment-1014660427)

Issue moved to [swagger-api/apidom #1076](https://github.com/swagger-api/apidom/issues/1076) via [**ZenHub**](https://www.zenhub.com/)

**Comment by char0n** [comment] 2022-08-09 07:16
Closing as duplicate of https://github.com/swagger-api/apidom/issues/1076

**Closed by char0n** 2022-08-09 07:16 UTC
