### ISSUE TITLE
oneOf causes a validation error, but I believe it to be valid

### ISSUE THREAD

**Issue by ponelat** [swagger-api/apidom#1638] opened 2022-06-22 13:03 UTC
### Q&A (please complete the following information)
editor-next.swagger.io

### To reproduce...

When using `oneOf`, we get a validation error: "oneOf must be a non-empty array of schemas". Although `anyOf` and `allOf` in the same place produces no errors.

### Expected behavior
No validation error

### Additional context or thoughts

```yml
asyncapi: '2.4.0'
info:
  title: oneOf error
  version: '1.0.0'
  description: |
    Weird oneOf error. Even though definition is good.
channels: {}

components:
  schemas:
    One:
      type: string
      example: 'one'
    Two:
      type: string
      example: 'two'
    Three:  # <---- Validation message: "oneOf must be a non-empty array of schemas"
      oneOf:
        - $ref: '#/components/schemas/One'
        - $ref: '#/components/schemas/Two'
 ```

**Comment by frantuma** [comment] 2023-07-31 11:13
closing as duplicate of (fixed) https://github.com/swagger-api/swagger-editor/issues/4026

**Closed by frantuma** 2023-07-31 11:13 UTC
